# Copyright 2015 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

import logging
from subiquitycore.model import BaseModel
from subiquitycore.utils import crypt_password


log = logging.getLogger('subiquitycore.models.locale')
localedata = 'data/localedata'

locale_format = """
# KEYBOARD CONFIGURATION FILE
# Generated by console-conf

# Consult the keyboard(5) manual page.

XKBMODEL="pc105"
XKB_LAYOUT="{layout}"
XKB_VARIANT="{variant}"
XKBOPTIONS=""

BACKSPACE="guess"
"""


class LocaleModel(BaseModel):
    """ Model representing system locale
    """
    signals = [
        ("Layout view",
         'menu:locale:main',
         'locale'),
        ("Variant view",
         'menu:locale:variant',
         'locale'),
    ]

    locale_menu = []
    _layout = ''
    _variant = ''

    def __init__(self, opts):
        self.opts = opts
        self.locales = self.setup_locales()

    def get_signals(self):
        return self.signals

    def get_menu(self):
        return self.locales

    def get_layouts(self):
        return self.locales['layouts']

    def get_variants(self):
        return self.locales['variants']

    def get_signal_by_name(self, selection):
        for x, y, z in self.get_menu():
            if x == selection:
                return y

    def set_effective_layout(self, selected, state, user_data):
        if state:
            self._layout = user_data

    @property
    def layout(self):
        return self._layout

    @property
    def variant(self):
        return self._variant

    def __repr__(self):
        return locale_format.format(layout=self.layout, variant=self.variant)

    def setup_locales(self):
        locales = {}
        layouts = []
        variants = {}
        with open(localedata, 'r') as localedata_fp:
            for line in localedata_fp:
                if not line.startswith('C*'):
                    continue

                line = line.rstrip()
                locale = line.split('*')
                if locale[1] == 'layout':
                    locale = line.split('*')
                    layouts.append([ locale[3], locale[2] ])
                if locale[1] == 'variant':
                    if locale[3] is not '':
                        if not locale[2] in variants:
                            variants[ locale[2] ] = []
                        variants[ locale[2] ].append([ locale[4], locale[3] ])

        locales['layouts'] = layouts
        locales['variants'] = variants

        return locales
