files: "(console_conf|subiquity|subiquitycore|vmtests|doc)"
repos:
  - repo: https://github.com/psf/black
    rev: 87928e6d6761a4a6d22250e1fee5601b3998086e  # 26.5.1
    hooks:
      - id: black
        files: "(console_conf|subiquity|subiquitycore|vmtests)"
  - repo: https://github.com/pycqa/isort
    rev: 131f4adcd5582bfc53928ab0d740eceb8b506b6c  # 9.0.1
    hooks:
      - id: isort
        name: isort
        files: "(console_conf|subiquity|subiquitycore|vmtests)"
  - repo: local
    hooks:
      - id: doc-spelling
        name: doc-spelling
        language: system
        entry: make -C doc spelling
        files: "doc/.*rst"
        pass_filenames: false
