name: subiquity
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  subiquity-loadkeys:
    command: usr/bin/subiquity-loadkeys
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: usr/bin/probert
  subiquity-service:
    command: usr/bin/subiquity-service
    daemon: simple
    restart-condition: always

parts:
  subiquity:
    plugin: python
    build-packages:
      - libsystemd-dev
      - lsb-release
      - pkg-config
      - python3-distutils-extra
      - python3-urwid
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
    stage-packages:
      - libc6
      - libnl-3-dev
      - libnl-genl-3-dev
      - libnl-route-3-dev
      - libsystemd0
      - iso-codes
      - lsb-release
      - python3-distutils-extra
      - python3-urwid
    python-packages:
      - attrs
      - pyyaml
      - systemd-python
      - pyudev==0.21.0
      - jsonschema==2.6.0
      #- urwid
    source: .
    source-type: git
  wrappers:
    plugin: dump
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/subiquity-loadkeys': usr/bin/subiquity-loadkeys
      'bin/curtin-journald-forwarder': usr/bin/curtin-journald-forwarder
      'bin/subiquity-service': usr/bin/subiquity-service
      'bin/probert': usr/bin/probert
    stage-packages: [libc6]
    stage:
      - usr/bin
    prime:
      - usr/bin
  users-and-groups:
    plugin: dump
    build-packages:
      - user-setup
    prepare: |
      echo "get passwd/user-default-groups" | \
        debconf-communicate user-setup | \
        cut -d ' ' -f 2- > users-and-groups
    stage-packages: [libc6]
    stage:
      - users-and-groups
  kbdnames:
    plugin: dump
    build-packages:
      - console-setup
      - locales
      - xkb-data-i18n
    stage-packages: [libc6]
    prepare: |
      /usr/share/console-setup/kbdnames-maker /usr/share/console-setup/KeyboardNames.pl > kbdnames.txt
    stage:
      - kbdnames.txt
