name: subiquity
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  subiquity-loadkeys:
    command: usr/bin/subiquity-loadkeys
  subiquity-configure-apt:
    command: usr/bin/subiquity-configure-apt
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: bin/probert
  subiquity-service:
    command: usr/bin/subiquity-service
    daemon: simple
    restart-condition: always

parts:
  curtin:
    plugin: python
    source-type: git
    source: git://git.launchpad.net/curtin
    source-branch: ubuntu/devel
    requirements: requirements.txt
    organize:
      'lib/python*/site-packages/usr/lib/curtin': 'usr/lib/'
    stage: [ "*", "-lib/python*/site-packages/_yaml.*.so" ]
    stage-packages: [libc6]
  subiquity:
    plugin: python
    build-packages:
      - libsystemd-dev
      - lsb-release
      - pkg-config
      - python3-distutils-extra
      - python3-urwid
    stage-packages:
      - libc6
      - libsystemd0
      - iso-codes
      - lsb-release
      - python3-distutils-extra
      - python3-urwid
      - python3-requests
      - python3-requests-unixsocket
      - ssh-import-id
    python-packages:
      - attrs
      - pyyaml
      - systemd-python
      #- urwid
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/subiquity-loadkeys': usr/bin/subiquity-loadkeys
      'bin/subiquity-service': usr/bin/subiquity-service
      'bin/subiquity-configure-apt': usr/bin/subiquity-configure-apt
  users-and-groups:
    plugin: dump
    build-packages:
      - user-setup
    override-build: |
      echo "get passwd/user-default-groups" | \
        debconf-communicate user-setup | \
        cut -d ' ' -f 2- > $SNAPCRAFT_PART_INSTALL/users-and-groups
      cp /usr/lib/user-setup/reserved-usernames $SNAPCRAFT_PART_INSTALL/
    stage-packages: [libc6]
    stage:
      - users-and-groups
      - reserved-usernames
  kbdnames:
    plugin: dump
    build-packages:
      - console-setup
      - locales
      - xkb-data-i18n
    stage-packages: [libc6]
    override-build: |
      /usr/share/console-setup/kbdnames-maker /usr/share/console-setup/KeyboardNames.pl > $SNAPCRAFT_PART_INSTALL/kbdnames.txt
    stage:
      - kbdnames.txt
  font:
    plugin: dump
    organize:
      font/subiquity.psf: subiquity.psf
    stage:
      - subiquity.psf
  probert:
    plugin: python
    build-packages: [python-setuptools, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    stage-packages: [libc6, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/CanonicalLtd/probert.git
    source-type: git
    source-commit: 31e973d130a137ef1713ac23a422af0e32108c01
    requirements: requirements.txt
