name: subiquity
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: bin/probert

parts:
  subiquity:
    plugin: python
    build-packages: [python3-distutils-extra]
    stage-packages: [python3-distutils-extra, curtin]
    python-packages:
      - urwid
      - pyyaml
      - pyudev
      - attrs
    source: .
    # snapcraft python plugin is crazy, fix everything
    install: |
      (cd $SNAPCRAFT_PART_INSTALL/lib/python3.*/site-packages && rm -rf easy_install.py pip* pkg_resources setuptools* wheel*)
      (cd $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages && rm -rf attr attrs* urwid* subiquitycore subiquity* pyudev* probert* console_conf*)
      mv $SNAPCRAFT_PART_INSTALL/lib/python3.*/site-packages/* $SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages
      rm -rf $SNAPCRAFT_PART_INSTALL/lib/python3.*
      mv $SNAPCRAFT_PART_INSTALL/share/locale $SNAPCRAFT_PART_INSTALL/usr/share/
      rmdir $SNAPCRAFT_PART_INSTALL/share
  wrappers:
    plugin: dump
    source: .
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
    prime:
      - usr/bin
  probert:
    plugin: python
    build-packages: [python-setuptools, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/CanonicalLtd/probert.git
    source-type: git
