name: subiquity
base: core18
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
    environment:
      PYTHONIOENCODING: utf-8
      SUBIQUITY_ROOT: $SNAP
  probert:
    command: bin/probert
  subiquity-server:
    command: usr/bin/subiquity-server
    daemon: simple
    restart-condition: always
    environment:
      PYTHONIOENCODING: utf-8
      SUBIQUITY_ROOT: $SNAP
      PYTHON: $SNAP/usr/bin/python3
  subiquity-service:
    command: usr/bin/subiquity-service
    daemon: simple
    restart-condition: always
    environment:
      PYTHONIOENCODING: utf-8
      SUBIQUITY_ROOT: $SNAP

parts:
  curtin:
    override-pull: |
      snapcraftctl pull
      PACKAGED_VERSION="$(git describe --long --abbrev=9 --match=[0-9][0-9]*)"
      sed -e "s,@@PACKAGED_VERSION@@,$PACKAGED_VERSION,g" -i curtin/version.py
    plugin: python
    source-type: git
    source: https://git.launchpad.net/curtin
    source-commit: 809817fdac257de1769e385a42aeaf3d5bcc2c60
    python-packages:
      - pyyaml==5.3.1
      - oauthlib
      - jsonschema
      - pyrsistent
    organize:
      'lib/python*/site-packages/usr/lib/curtin': 'usr/lib/'
    stage:
     - "*"
     - "-lib/python*/site-packages/_yaml.*.so"
     - "-lib/python*/site-packages/jsonschema"
  apport:
    plugin: python
    source-type: bzr
    source: lp:~ubuntu-core-dev/ubuntu/focal/apport/ubuntu
    build-packages:
      - python3-distutils-extra
      - python3-apt
      - python3-httplib2
      - python3-problem-report
      - python3-requests-unixsocket
    stage-packages:
      - python3-distutils-extra
      - python3-apt
      - python3-httplib2
      - python3-problem-report
      - python3-requests-unixsocket
    stage:
      - "lib/python*/site-packages/"
      - "-lib/python*/site-packages/etc/*"
      - "-lib/python*/site-packages/lib/*"
      - "share/apport/general-hooks/"
      - "usr/"
  subiquity:
    plugin: python
    build-packages:
      - libsystemd-dev
      - lsb-release
      - pkg-config
      - python3-urwid
    stage-packages:
      - cloud-init
      - libsystemd0
      - iso-codes
      - lsb-release
      - python3-bson
      - python3-urwid
      - python3-requests
      - python3-requests-unixsocket
      - ssh-import-id
    python-packages:
      - attrs
      - pyyaml==5.3.1
      - systemd-python
      - aiohttp
      - yarl==1.5.1
      #- urwid
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/subiquity-service': usr/bin/subiquity-service
      'bin/subiquity-server': usr/bin/subiquity-server
  users-and-groups:
    plugin: nil
    build-packages:
      - user-setup
    override-build: |
      echo "get passwd/user-default-groups" | \
        debconf-communicate user-setup | \
        cut -d ' ' -f 2- > $SNAPCRAFT_PART_INSTALL/users-and-groups
      cp /usr/lib/user-setup/reserved-usernames $SNAPCRAFT_PART_INSTALL/
    stage:
      - users-and-groups
      - reserved-usernames
  keyboard-data:
    plugin: nil
    build-packages:
      - console-setup
      - locales
      - xkb-data-i18n
      - python3-attr
      - python3-yaml
    override-build: PYTHONPATH=$SNAPCRAFT_PROJECT_DIR/ $SNAPCRAFT_PROJECT_DIR/scripts/make-kbd-info.py
    stage:
      - kbds/
  font:
    plugin: dump
    source: ./
    source-type: git
    organize:
      font/subiquity.psf: subiquity.psf
    stage:
      - subiquity.psf
  languagelists:
    plugin: nil
    build-packages:
      - localechooser-data
    override-build: |
      grep '^path-exclude=.*LC_MESSAGES.*' /etc/dpkg/dpkg.cfg.d/excludes && {
        sed -i 's/^path-exclude.*LC_MESSAGES.*/#\0/g' /etc/dpkg/dpkg.cfg.d/excludes
        apt-get -y install --reinstall iso-codes
      } || true
      $SNAPCRAFT_PROJECT_DIR/scripts/make-language-lists $SNAPCRAFT_PROJECT_DIR/po > $SNAPCRAFT_PART_INSTALL/languagelist
    stage:
      - languagelist
  probert:
    plugin: python
    build-packages: [python-setuptools, build-essential, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/canonical/probert.git
    source-type: git
    source-commit: 2bb505172b5f97372eb1abd12ced4629e852504b
    requirements: [requirements.txt]
