name: subiquity
base: core18
version: git
summary: Ubuntu installer
description: The Ubuntu server installer
confinement: classic

apps:
  subiquity:
    command: usr/bin/subiquity
  subiquity-loadkeys:
    command: usr/bin/subiquity-loadkeys
  subiquity-configure-apt:
    command: usr/bin/subiquity-configure-apt
  subiquity-configure-run:
    command: usr/bin/subiquity-configure-run
  console-conf:
    command: usr/bin/console-conf
  probert:
    command: bin/probert
  subiquity-service:
    command: usr/bin/subiquity-service
    daemon: simple
    restart-condition: always

parts:
  curtin:
    plugin: python
    source-type: git
    source: git://git.launchpad.net/curtin
    source-commit: 0832e4efaa6259cbdfd197379bc5da943810d763
    requirements: [requirements.txt]
    organize:
      'lib/python*/site-packages/usr/lib/curtin': 'usr/lib/'
    stage:
     - "*"
     - "-lib/python*/site-packages/_yaml.*.so"
     - "-lib/python*/site-packages/jsonschema"
    stage-packages:
     - libc6
     - try:
       - efibootmgr
  apport-hooks:
    plugin: nil
    stage-packages:
      - apport
    stage:
      - usr/share/apport/general-hooks/*
  subiquity:
    plugin: python
    build-packages:
      - libsystemd-dev
      - lsb-release
      - pkg-config
      - python3-distutils-extra
      - python3-urwid
    stage-packages:
      - cloud-init
      - libc6
      - libsystemd0
      - iso-codes
      - lsb-release
      - python3-apport
      - python3-bson
      - python3-distutils-extra
      - python3-urwid
      - python3-requests
      - python3-requests-unixsocket
      - ssh-import-id
    python-packages:
      - attrs
      - pyyaml
      - systemd-python
      #- urwid
    source: .
    source-type: git
    organize:
      'bin/console-conf-tui': usr/bin/console-conf
      'bin/subiquity-tui': usr/bin/subiquity
      'bin/subiquity-loadkeys': usr/bin/subiquity-loadkeys
      'bin/subiquity-service': usr/bin/subiquity-service
      'bin/subiquity-configure-apt': usr/bin/subiquity-configure-apt
      'bin/subiquity-configure-run': usr/bin/subiquity-configure-run
  users-and-groups:
    plugin: nil
    build-packages:
      - user-setup
    override-build: |
      echo "get passwd/user-default-groups" | \
        debconf-communicate user-setup | \
        cut -d ' ' -f 2- > $SNAPCRAFT_PART_INSTALL/users-and-groups
      cp /usr/lib/user-setup/reserved-usernames $SNAPCRAFT_PART_INSTALL/
    stage-packages: [libc6]
    stage:
      - users-and-groups
      - reserved-usernames
  kbdnames:
    plugin: nil
    build-packages:
      - console-setup
      - locales
      - xkb-data-i18n
    stage-packages: [libc6]
    override-build: |
      /usr/share/console-setup/kbdnames-maker /usr/share/console-setup/KeyboardNames.pl > $SNAPCRAFT_PART_INSTALL/kbdnames.txt
    stage:
      - kbdnames.txt
  font:
    plugin: dump
    source: ./
    organize:
      font/subiquity.psf: subiquity.psf
    stage:
      - subiquity.psf
  probert:
    plugin: python
    build-packages: [python-setuptools, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    stage-packages: [libc6, libnl-3-dev, libnl-genl-3-dev, libnl-route-3-dev]
    source: https://github.com/CanonicalLtd/probert.git
    source-type: git
    source-commit: 4793e16ea1c397c44e115dc90eafa60df0947d5c
    requirements: [requirements.txt]
