#cloud-config
autoinstall:
  version: 1

  identity:
    realname: ''
    hostname: ubuntu
    username: ubuntu
    password: '$6$wdAcoXrU039hKYPd$508Qvbe7ObUnxoj15DRCkzC3qO7edjH0VV7BPNRDYK4QR8ofJaEEF2heacn0QgD.f8pO8SNp83XNdWG6tocBM1'

  source:
    id: ubuntu-server-minimal

  early-commands:
    - apt-get install -y zfsutils-linux

  late-commands:
    # Let's avoid recreating LP: #1993318
    - zpool set cachefile= rpool
    - cp /etc/zfs/zpool.cache "/target/etc/zfs/"
    - mkdir -p "/etc/zfs/zfs-list.cache" "/target/etc/zfs/zfs-list.cache"
    - truncate -s 0 /etc/zfs/zfs-list.cache/rpool
    - >-
      env -i
      ZEVENT_POOL=rpool
      ZED_ZEDLET_DIR=/etc/zfs/zed.d
      ZEVENT_SUBCLASS=history_event
      ZFS=zfs
      ZEVENT_HISTORY_INTERNAL_NAME=create
      /etc/zfs/zed.d/history_event-zfs-list-cacher.sh
    - >-
      sh -c
      'sed -E "s|\t/target/?|\t/|g" "/etc/zfs/zfs-list.cache/rpool" > "/target/etc/zfs/zfs-list.cache/rpool"'
    - rm -f "/etc/zfs/zfs-list.cache/rpool"

  storage:
    layout:
      name: zfs
