#!/usr/bin/python3

import glob
import gzip
import os


translations = set()
for fname in glob.glob('po/*.po'):
    translations.add(os.path.splitext(os.path.basename(fname))[0])

print('found translations', translations)
    
console_langs = open('languagelist-console', 'w')
ssh_langs = open('languagelist-ssh', 'w')
data = gzip.open('/usr/share/localechooser/languagelist.data.gz', mode='rt')

for line in data:
    level, code, name, desc = line.strip().split(':')
    if code not in translations:
        continue
    level = int(level)
    new_line = "{}:{}\n".format(code, desc)
    ssh_langs.write(new_line)
    if level <= 2:
        console_langs.write(new_line)

console_langs.close()
ssh_langs.close()
data.close()
