name: Main Documentation Checks

on:
  pull_request:
    paths:
      - 'doc/**'
  push:
    paths:
      - 'doc/**'
  workflow_dispatch:
    paths:
      - 'doc/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true  

jobs:
  documentation-checks:
    # FIXME convert to following a tag when available
    # https://redirect.github.com/canonical/documentation-workflows/issues/6
    uses: canonical/documentation-workflows/.github/workflows/documentation-checks.yaml@309dd382b6a07cbd23d84e3912fb05e6bc1f4ffb  # main
    with:
      working-directory: 'doc'
