name: cla-check

on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-20.04
    steps:
      - name: debug action
        uses: hmarr/debug-action@v2
      - name: Check if CLA signed
        uses: canonical/has-signed-canonical-cla@v1
        with:
          accept-existing-contributors: true
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
