name: TICS
# on:
#   push:
#     branches:
#       - main

# FIXME demote to only run weekly

on: [pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  TICS:
    runs-on: [self-hosted, linux, amd64, tiobe, jammy]
    steps:
      - name: Checkout the project
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dependencies
        run: |
          sudo ./scripts/installdeps.sh
          sudo apt install pylint

      - name: Coverage
        run: |
          make unit

      - name: pylint is installed, right?
        run: command -v pylint

      - name: Run TICS analysis with github-action
        uses: tiobe/tics-github-action@v3
        with:
          mode: qserver
          project: subiquity
          branchdir: .
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          installTics: true
