#!/bin/bash
# Copyright 2015 Canonical, Ltd.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as
# published by the Free Software Foundation, either version 3 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

ARCH=${ARCH-"`uname -m`"}
MEM=${MEM-"1024"}
INSTALLER=${INSTALLER-"installer.img"}
TARGET=${TARGET-"target.img"}
SPORT=2445

QEMU=`which qemu-system-$ARCH`;
if [ -z $QEMU ]; then
   case $ARCH in
      i386|x86_64) PKG=qemu-system-x86 ;;
      arm*) PKG=qemu-system-arm ;;
      ppc*) PKG=qemu-system-ppc ;;
      *)
         echo "Unsupported arch: $ARCH";
         exit 1;
         ;;
    esac
    sudo apt-get install $PKG || {
       echo "Failed to install qemu-system package $PKG";
       exit 1;
    }
fi

# always recreate the target image
qemu-img create -f raw ${TARGET} 10G

# TODO, curses should work, but my xmonad setup blocks using it
sudo qemu-system-$ARCH -smp 2 -m $MEM -enable-kvm \
                       -drive cache=unsafe,if=virtio,file=$INSTALLER,serial=QM_INSTALL_01 \
                       -drive cache=unsafe,if=virtio,file=$TARGET,serial=QM_TARGET_01 \
                       -net nic,model=e1000 \
                       -net nic,model=virtio \
                       -net nic,model=i82559er \
                       -net user \
                       -monitor telnet:127.0.0.1:2446,server,nowait -serial stdio
#sudo qemu-system-$ARCH -m $MEM -enable-kvm -hda $INSTALLER -hdb $TARGET \
#                       -monitor telnet:127.0.0.1:2446,server,nowait -curses

exit $?
